---
- name: update apt cache
  apt: update_cache=yes
- name: install postfix and libsasl2-modules
  apt: name={{item}} state=present
  with_items:
    - postfix
    - libsasl2-modules
- name: template files
  template:
    src: "{{ role_path }}/templates/{{item.src}}.j2"
    dest: "/etc/{{item.dest}}"
    mode: 0644
  with_items:
  - { src: "main.cf", dest: "postfix/main.cf" }
  - { src: "mailname", dest: "mailname" }
  notify:
  - restart postfix
- name: update aliases file
  template:
    src: "{{ role_path }}/templates/aliases.j2"
    dest: "/etc/aliases"
    mode: 0644
  notify:
  - process aliases
  - restart postfix
- name: update sasl_passwd
  sasl_passwd:
    name: "/etc/postfix/sasl_passwd"
    host: "{{relayhost}}"
    user: "{{smtp_user}}"
    password: "{{smtp_password}}"
  notify:
  - restart postfix
- name: postfix enabled and running
  service: name=postfix enabled=yes state=started
